### ISSUE TITLE
Doctrine connection exception

### ISSUE THREAD

**Issue by martiis** [ongr-io/SettingsBundle#100]
When I tried to login I received:
`
An exception occured in driver: SQLSTATE[42000] [1049] Unknown database 'ongr'
500 Internal Server Error - ConnectionException
`

Doctrine tries to check version of sql server. To avoid this check Doctrine's configuration has to have `server_version` defined. Maybe add this notice to doc's?

**Comment by emaslak** [comment]
Closed in #140
