### ISSUE TITLE
Identical files.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/SettingsBundle#113]
These two have exactly same contents.
https://github.com/ongr-io/SettingsBundle/blob/master/README.rst
https://github.com/ongr-io/SettingsBundle/blob/master/Resources/doc/index.rst

**Comment by mindaugasbarysas** [comment]
Is that a bad thing?

**Comment by GrandLTU** [comment]
Well yes, if they are supposed to be identical every time changes needs to made we need to remember to update both. 

I would propose to leave a short description in readme with all the badges and link to readthedocs as this is where index.rst is used.

**Comment by mindaugasbarysas** [comment]
You have a point, but having a readme with more than just a link would be nice. Maybe a symlink could be a solution?

**Comment by GrandLTU** [comment]
Its possibility but i am not sure if all file systems support relative links.

**Comment by mindaugasbarysas** [comment]
They all do.

**Comment by GrandLTU** [comment]
Ok then :)

**Comment by mindaugasbarysas** [comment]
Ok, on the other hand, there are some things that made me reconsider my position, this is a valid ticket, and readme and index should be separate files. See #126
