### ISSUE TITLE
When listing dependencies 1 is omitted.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/SettingsBundle#114]
https://github.com/ongr-io/SettingsBundle/blame/master/Resources/doc/index.rst#L75
Here are 4 and in but in code example 5 are listed.

Either do not list bundles explicitly for a second time or mention all the bundles, and i am for the former as this list kinda does not have any purpose without declaring reason for including those bundles.

**Comment by lmikelionis** [comment]
I'm for adding missing bundles. Because user will be notified, that these bundles must be included.
