### ISSUE TITLE
Skipped return type in docs. Misleading function name.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/SettingsBundle#115]
https://github.com/ongr-io/SettingsBundle/blob/master/Document/Setting.php#L186

Only description is provided.

**Comment by mindaugasbarysas** [comment]
It is also worth mentioning that when calling jsonSerialize one would expect to get a JSON string, but instead array is returned. Function name should also be changed to something more appropriate.

**Comment by mindaugasbarysas** [comment]
Disregard my comment, it's the name of a method defined in `JsonSerializable` interface.
