### ISSUE TITLE
Clarification required.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/SettingsBundle#117]
https://github.com/ongr-io/SettingsBundle/blame/master/Resources/doc/index.rst#L153

If it is only recommended when and why should i skip this command? Why is it recommended?

**Comment by mindaugasbarysas** [comment]
@lmikelionis could you take a look at this? "Blame" indicates that you wrote this :)

**Comment by lmikelionis** [comment]
As it says: " so your "working" data won't mix up with settings".
In other words its a good practice to have your config data and shop or other data, that is doing actual business, be kept in different places.
Am I answering to correct qustion? :)

**Comment by mindaugasbarysas** [comment]
If I understand correctly, @GrandLTU was refering to the "Also it's recommended to install projects' assets:" part.

**Comment by lmikelionis** [comment]
Ok, its recomended, beacause user might do this step later.

**Comment by mindaugasbarysas** [comment]
But it is not to be omitted?

**Comment by lmikelionis** [comment]
Yes, at some point assets must be installed.

**Comment by mindaugasbarysas** [comment]
In that case I suggest making the recommendation a requirement ;)
