### ISSUE TITLE
Do we really need travis badge in readthedocs?

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/SettingsBundle#126]

**Comment by mindaugasbarysas** [comment]
IMHO Badges (build, coverage, scrutinizer scores, etc.) are not needed and should be omitted in documentation, they belong in the README files displayed in Github. I can not think of any reason why they would be *needed* in a documentation. My reasoning is as follows:

1. Documentation needs to reflect upon functionality of the software. It does not have to reflect the status or the quality of the software documented, even less so about it's current state. 
2. Documentation is (mostly) static. It is written once, and is updated when the need arises (breaking changes, new functionality, serious bugs or caveats are discovered that need documenting, etc.)
3. README is something that a would-be advanced user / developer sees when opening the source for forking / looking through. Badges provide at-a-glance information whether the software works, whether it is tested, whether if it is of a high quality. It is a "greeter". Documentation, on the other hand, serves a different purpose altogether - it is meant to provide in-depth information about how and why software works.

What would be your opinion on this matter, @saimaz , @tautrimas ?

**Comment by tautrimas** [comment]
I agree with @mindaugasbarysas. Dynamic content does not belong to doc.
