### ISSUE TITLE
Is "warning" warranted here?

### ISSUE THREAD

**Issue by emaslak** [ongr-io/SettingsBundle#130]
There is also "important" admonition. Wouldn't it be enough to use one of them?
https://github.com/ongr-io/SettingsBundle/blame/8e28df2c916ff0b121bdaf339da90e701357897a/Resources/doc/index.rst#L91-L92

**Comment by lmikelionis** [comment]
It's verry important, to get users attention.

**Comment by mindaugasbarysas** [comment]
Wouldn't "note" be enough? Or could we omit "IMPORTANT"?

**Comment by GrandLTU** [comment]
I am for removing "IMPORTANT" as the warning markup already catches users' attention.

**Comment by lmikelionis** [comment]
So probably we have to remove it :)

**Comment by mindaugasbarysas** [comment]
I think we have reached an agreement here, removing the "question" tag.
