### ISSUE TITLE
Unclear functionality of Environment variables.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/SettingsBundle#131]
There are no examples or anything just few statements about something being prefixed with ONGR_ will overwrite something. Also a link to Symfony environment variables documentation could help.

**Comment by mindaugasbarysas** [comment]
Could you please point me to the concrete location? Thanks.

**Comment by GrandLTU** [comment]
https://ongr.readthedocs.org/en/latest/components/SettingsBundle/env_variable.html
