### ISSUE TITLE
Event dispatcher missing

### ISSUE THREAD

**Issue by einorler** [ongr-io/SettingsBundle#172]
Latest versions of `FilterManager` require event dispatcher instance to be passed as a third parameter in its constructor. The bundle does not provide that in its compiler pass:
https://github.com/ongr-io/SettingsBundle/blob/2e87b941f5cee38c55dff6d1412e820da97da8af/DependencyInjection/Compiler/SettingsManagerPass.php#L27

**Comment by saimaz** [comment]
Resolved in 1.0
